# The signing keys.
#
# Every file sent to central systems is signed with our private key and
# encrypted with theirs. Without these the gateway can build files and process
# inbound, but cannot send.
#
# Unlike the database password, these are NOT generated by Terraform. They are
# created once by a human with gpg and loaded out of band. A private key in a
# Terraform state file is a private key in the state bucket, in every state
# backup, and in the plan output of anyone who runs terraform plan.
#
# Terraform creates the containers and the access grants. It never sees the
# values.

resource "google_secret_manager_secret" "gpg_private_key" {
  secret_id = "${local.prefix}-gpg-private-key"

  replication {
    user_managed {
      replicas {
        location = var.region
      }
    }
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret" "gpg_passphrase" {
  secret_id = "${local.prefix}-gpg-passphrase"

  replication {
    user_managed {
      replicas {
        location = var.region
      }
    }
  }

  depends_on = [google_project_service.apis]
}

# Central Services' public key. Not secret -- it is published -- but held here
# so the container receives it the same way it receives everything else, and
# so rotating it is a secret version rather than an image rebuild.
resource "google_secret_manager_secret" "gpg_recipient_key" {
  secret_id = "${local.prefix}-gpg-recipient-key"

  replication {
    user_managed {
      replicas {
        location = var.region
      }
    }
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_iam_member" "gateway_gpg" {
  for_each = {
    private_key   = google_secret_manager_secret.gpg_private_key.secret_id
    passphrase    = google_secret_manager_secret.gpg_passphrase.secret_id
    recipient_key = google_secret_manager_secret.gpg_recipient_key.secret_id
  }

  secret_id = each.value
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.gateway.email}"
}